name: Nexus ERP - Production Environment
values:
  - key: baseUrl
    value: 'https://your-production-domain.com/api'
  - key: rootUrl
    value: 'https://your-production-domain.com'
  - key: authToken
    value: ''
  - key: adminEmail
    value: admin@fundsroom.com
  - key: adminPassword
    value: Admin@123
  - key: salesEmail
    value: sales@fundsroom.com
  - key: salesPassword
    value: Sales@123
  - key: warehouseEmail
    value: warehouse@fundsroom.com
  - key: warehousePassword
    value: Warehouse@123
  - key: accountsEmail
    value: accounts@fundsroom.com
  - key: accountsPassword
    value: Accounts@123
  - key: customerId
    value: ''
  - key: productId
    value: ''
  - key: challanId
    value: ''
